#!/bin/zsh
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
n=9
m=$(xrandr | grep " connected" | awk '{print $1}' | wc -l)
d=1
i=0
for s in $(xrandr | grep " connected" | awk '{print $1}'); do
    desktops=""
    for i in $(seq 1 $(($n/$m))); do
        desktops="$desktops $d"
        d=$(($d+1))
    done
    cmd="bspc monitor $s -d $desktops"
    zsh -c $cmd
done

## FIXME i should be so much cleverer...
xrandr --output eDP1 --mode 2048x1152



xrget() {
    xrdb -query | grep $1 | awk '{print $NF}'
}
bspc config top_padding 40
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 10
bspc config border_width         2
#bspc config auto_alternate              true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config normal_border_color $(xrget color13)
bspc config focused_border_color $(xrget color5)
bspc config active_border_color $(xrget color10)
bspc config presel_feedback_color $(xrget color9)

for r in $(bspc rule --list | awk '{print $1}'); do
    bspc rule --remove $r
done

pgrep -f scratchpad && pkill -f scratchpad
bspc rule -a 'scratchpad:*' state=fullscreen sticky=on hidden=on \
    follow=on

bspc rule -a Spotify desktop='^1' follow=on
bspc rule -a Signal desktop='^2' follow=on
bspc rule -a Slack desktop='^4' follow=on
bspc rule -a Telegram desktop='^9' follow=on
bspc rule -a Chromium desktop='^7'
bspc rule -a Firefox desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a xeyes state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

. ~/.profile
kil sxhkd
kil dunst
kil blueberry-tray
pgrep xcape && killall xcape
xcape -t 250 -e 'Shift_L=F12' >/dev/null 2>&1 &
xcape -t 250 -e 'Shift_R=F10' >/dev/null 2>&1 &
#xcape -t 250  -e 'Super_L=Super_L|d' >/dev/null 2>&1 &
#xcape -t 250 -e 'Super_R=Super_R|r' >/dev/null 2>&1 &
#[[ "-r" != "$1" ]] && $HOME/bin/run_startup
startup_dir="$HOME/bin/startup"
log_dir="/tmp/bspwm-$USER"
[[ -d $log_dir ]] || mkdir -p $log_dir
for s in $startup_dir/*; do
    [[ -x $s ]] && $s restart > $log_dir/$(basename $s).log 2>&1
done

libinput-gestures-setup restart
pgrep xscreensaver && pkill xscreensaver
xscreensaver -nosplash >/dev/null 2>&1 & disown
