#! /bin/bash
#[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

reload_dunst() {
    pkill dunst
    dunst & #\
	#-frame_width 0 \
    #    -lb "${color0}" \
    #    -nb "${color0}" \
    #    -cb "${color0}" \
    #    -lf "${color7}" \
    #    -bf "${color7}" \
    #    -cf "${color7}" \
    #    -nf "${color7}" &
}

# autorandr.service should handle this
~/bin/xmm
~/bin/monitors
~/bin/wp
. ~/.profile
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
#. "${HOME}/.cache/wal/colors.sh"
kil sxhkd



#for m in $(bspc query -M); do
    #bspc monitor $m -d $m/I/$m $m/two $m/III $m/IV $m/V $m/VI $m/VII $m/VIII $m/IX
    #bspc monitor $m -d one/$m two/$m three/$m four/$m five/$m six/$m seven/$m eight/$m nine/$m
    #bspc monitor $m -d 1 2 3 4 5 6 7 8 9
    #bspc monitor $m -d a/$m b/$m c/$m d/$m e/$m f/$m g/$m h/$m i/$m

#done
#bspc monitor -d \~ 1 2 3 4 5 6 7 8 9 10
#for m in $(bspc query -M); do
#    #bspc monitor $m -d a b c d
#    bspc monitor $m -d \~ 1 2 3 4 5 6 7 8 9 10
#    bspc monitor -f $m
#    bspc desktop -f 1
#done

D=12
let i=1
for m in $(bspc query -M); do bspc monitor $m -d \~ ; done
while [[ $i -le $D ]]; do
    for m in $(bspc query -M); do
        bspc monitor $m -a $i
        let i++
    done
done

bspc config border_width            4
bspc config window_gap              24

bspc config top_padding 4
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle false
bspc config focus_by_distance       true
bspc config adaptive_raise          true
bspc config normal_frame_opacity    0.01
bspc config focused_frame_opacity   1.00
bspc config focus_follows_pointer   true

bspc config click_to_focus        button1
bspc config pointer_modifier      mod4

# source the colors.
# Set the border colors.
bspc config presel_feedback_color "$color1"


bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'
#bspc config normal_border_color "$color8"
#bspc config focused_border_color "$color15"
#bspc config presel_border_color "$color3"
#bspc config normal_sticky_border_color '#4e4e4e'
#bspc config focused_sticky_border_color "$color12"
#bspc config urgent_border_color "$color9"

bspc config pointer_modifier mod4
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -r *
# workspace 1
bspc rule -a Slack desktop=2
bspc rule -a TelegramDesktop desktop=2
bspc rule -a Spotify desktop=1
bspc rule -a Mailspring desktop=3
bspc rule -a Chronos desktop=3

#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a mpv state=floating
#bspc rule -a MuPDF state=floating
#bspc rule -a alacritty:stick state=floating sticky=on center
#bspc rule -a alacritty:stick1 state=floating sticky=on
#bspc rule -a alacritty:stick2 state=floating sticky=on

#bspc rule -a Alacritty:scratchy sticky=on state=floating \
#    rectangle=widthxheight+Xoffset+Yoffset

bspc rule -a Pavucontrol state=floating sticky=on
# bspc rule -a Firefox desktop=^1 follow=on
#[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

~/bin/pb

kil cbatticon
kil nm-applet
kil pasystray
reload_dunst
~/bin/splash
bspc desktop -f 2
kil slack
bspc desktop -f 3
#kil /opt/chronos/chronos
#kil mailspring
#~/bin/spotifyify
bspc desktop -f 1
~/bin/spotifyify
