#!/bin/bash

gcalcli agenda --nocolor "`date`" | head -2 | tail -1 | \
    sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g"

#IFS=$'\n' agenda=($(gcalcli --nocolor agenda))
#for a in ${agenda[@]}; do
#    #[[ $(date "+%a %b %d") =~ $a ]] && echo $a
#    echo $a
#    sleep 1
#done
